// Game State
let gameState = {
    mode: 'normal', // 'normal' or 'pro'
    currentLevel: 0,
    score: 0,
    startTime: null,
    timerInterval: null,
    ignoredFiles: [],
    wrongAttempts: 0
};

// Levels configuration
const levels = [
    {
        name: "Beginner Basics",
        files: [
            { name: "index.html", icon: "📄", shouldIgnore: false, content: '<!DOCTYPE html>\n<html>\n<head>\n  <title>My App</title>\n</head>\n<body>\n  <h1>Hello World</h1>\n</body>\n</html>' },
            { name: "style.css", icon: "🎨", shouldIgnore: false, content: 'body {\n  font-family: Arial;\n  margin: 0;\n  padding: 20px;\n}' },
            { name: "node_modules", icon: "📁", shouldIgnore: true, content: '[Directory containing 1,247 packages]\n\nThis folder is auto-generated by npm install.\nNever commit this to version control!' },
            { name: ".env", icon: "⚙️", shouldIgnore: true, content: 'DATABASE_URL=postgres://localhost:5432/mydb\nAPI_KEY=sk_live_abc123xyz789\nSECRET_TOKEN=super_secret_value' },
            { name: "app.js", icon: "📜", shouldIgnore: false, content: 'const express = require("express");\nconst app = express();\n\napp.get("/", (req, res) => {\n  res.send("Hello!");\n});\n\napp.listen(3000);' }
        ]
    },
    {
        name: "Python Project",
        files: [
            { name: "main.py", icon: "🐍", shouldIgnore: false, content: 'from flask import Flask\n\napp = Flask(__name__)\n\n@app.route("/")\ndef hello():\n    return "Hello, World!"' },
            { name: "__pycache__", icon: "📁", shouldIgnore: true, content: '[Directory containing compiled Python bytecode]\n\nPython creates these automatically.\nShould always be gitignored.' },
            { name: "requirements.txt", icon: "📄", shouldIgnore: false, content: 'flask==2.0.1\nrequests==2.26.0\npython-dotenv==0.19.0' },
            { name: ".env", icon: "⚙️", shouldIgnore: true, content: 'FLASK_SECRET=xK9#mP2$vL5@nQ8\nOPENAI_API_KEY=sk-proj-abc123xyz\nDATABASE_PASSWORD=admin123' },
            { name: "venv", icon: "📁", shouldIgnore: true, content: '[Python virtual environment]\n\nContains Python interpreter and packages.\nNever commit to version control!' },
            { name: "README.md", icon: "📝", shouldIgnore: false, content: '# My Python App\n\nA simple Flask application.\n\n## Installation\n```\npip install -r requirements.txt\n```' }
        ]
    },
    {
        name: "Full Stack App",
        files: [
            { name: "package.json", icon: "📦", shouldIgnore: false, content: '{\n  "name": "my-app",\n  "version": "1.0.0",\n  "scripts": {\n    "start": "node server.js"\n  }\n}' },
            { name: "node_modules", icon: "📁", shouldIgnore: true, content: '[Directory: 2,341 packages, 189MB]\n\nRun npm install to regenerate.' },
            { name: ".env.local", icon: "⚙️", shouldIgnore: true, content: 'NEXT_PUBLIC_API_URL=http://localhost:3000\nSTRIPE_SECRET_KEY=sk_test_51ABC123\nJWT_SECRET=my-super-secret-jwt-key' },
            { name: "dist", icon: "📁", shouldIgnore: true, content: '[Build output directory]\n\nGenerated by npm run build.\nShould be gitignored.' },
            { name: ".next", icon: "📁", shouldIgnore: true, content: '[Next.js build cache]\n\nAuto-generated, always ignore.' },
            { name: "src/index.tsx", icon: "⚛️", shouldIgnore: false, content: 'import React from "react";\nimport ReactDOM from "react-dom";\nimport App from "./App";\n\nReactDOM.render(<App />, document.getElementById("root"));' },
            { name: "tsconfig.json", icon: "📄", shouldIgnore: false, content: '{\n  "compilerOptions": {\n    "target": "ES6",\n    "strict": true\n  }\n}' },
            { name: ".DS_Store", icon: "🍎", shouldIgnore: true, content: '[macOS system file]\n\nStores folder view settings.\nAlways ignore on all projects.' }
        ]
    },
    {
        name: "DevOps Config",
        files: [
            { name: "Dockerfile", icon: "🐳", shouldIgnore: false, content: 'FROM node:18-alpine\nWORKDIR /app\nCOPY package*.json ./\nRUN npm install\nCOPY . .\nEXPOSE 3000\nCMD ["npm", "start"]' },
            { name: "docker-compose.yml", icon: "🐳", shouldIgnore: false, content: 'version: "3.8"\nservices:\n  app:\n    build: .\n    ports:\n      - "3000:3000"' },
            { name: ".env.production", icon: "⚙️", shouldIgnore: true, content: 'AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE\nAWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY\nDATABASE_URL=postgres://prod-db.aws.com/main' },
            { name: "secrets.yaml", icon: "🔐", shouldIgnore: true, content: 'api_keys:\n  stripe: sk_live_realkey123\n  sendgrid: SG.actualkey456\npasswords:\n  admin: supersecret789' },
            { name: "*.log", icon: "📋", shouldIgnore: true, content: '[2024-01-15 10:23:45] INFO: Server started\n[2024-01-15 10:23:46] DEBUG: Connected to DB\n[2024-01-15 10:23:47] ERROR: Something went wrong' },
            { name: ".terraform", icon: "📁", shouldIgnore: true, content: '[Terraform state and cache]\n\nContains sensitive state info.\nMust be gitignored!' },
            { name: "main.tf", icon: "🏗️", shouldIgnore: false, content: 'provider "aws" {\n  region = "us-east-1"\n}\n\nresource "aws_instance" "web" {\n  ami = "ami-123456"\n}' },
            { name: "coverage", icon: "📁", shouldIgnore: true, content: '[Test coverage reports]\n\nGenerated by test runner.\nShould be gitignored.' }
        ]
    },
    {
        name: "Pro Challenge",
        files: [
            { name: "config.js", icon: "📜", shouldIgnore: false, content: 'module.exports = {\n  port: process.env.PORT || 3000,\n  env: process.env.NODE_ENV || "development",\n  logLevel: "info"\n};' },
            { name: "settings.json", icon: "⚙️", shouldIgnore: true, content: '{\n  "apiKey": "pk_live_51HG8kw2eZvKYlo2CkqZ0x",\n  "secretKey": "sk_live_51HG8kwSecret123456",\n  "webhookSecret": "whsec_abcdef123456"\n}' },
            { name: "database.js", icon: "📜", shouldIgnore: false, content: 'const mongoose = require("mongoose");\n\nconst connectDB = async () => {\n  await mongoose.connect(process.env.DB_URI);\n};\n\nmodule.exports = connectDB;' },
            { name: "credentials.json", icon: "🔑", shouldIgnore: true, content: '{\n  "type": "service_account",\n  "project_id": "my-project-123",\n  "private_key_id": "abc123",\n  "private_key": "-----BEGIN PRIVATE KEY-----\\nMIIEvQIBADANBg..."\n}' },
            { name: "utils.js", icon: "📜", shouldIgnore: false, content: 'const formatDate = (date) => {\n  return new Date(date).toLocaleDateString();\n};\n\nconst slugify = (text) => {\n  return text.toLowerCase().replace(/\\s+/g, "-");\n};\n\nmodule.exports = { formatDate, slugify };' },
            { name: "temp_keys.txt", icon: "📄", shouldIgnore: true, content: 'TEMPORARY API KEYS - DELETE AFTER USE\n\nGitHub Token: ghp_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\nNPM Token: npm_xyzABC123456789\nAWS Key: AKIA1234567890EXAMPLE' },
            { name: "server.js", icon: "📜", shouldIgnore: false, content: 'const express = require("express");\nconst config = require("./config");\nconst connectDB = require("./database");\n\nconst app = express();\nconnectDB();\n\napp.listen(config.port);' },
            { name: ".cache", icon: "📁", shouldIgnore: true, content: '[Application cache directory]\n\nTemporary files, should be ignored.' },
            { name: "id_rsa", icon: "🔑", shouldIgnore: true, content: '-----BEGIN OPENSSH PRIVATE KEY-----\nb3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAA...\nThis is a private SSH key!\nNEVER commit this!\n-----END OPENSSH PRIVATE KEY-----' },
            { name: "README.md", icon: "📝", shouldIgnore: false, content: '# My Awesome Project\n\nThis is a full-stack application.\n\n## Getting Started\n\n1. Clone the repo\n2. Run `npm install`\n3. Create `.env` file\n4. Run `npm start`' }
        ]
    }
];

// File icons based on extension
function getFileIcon(filename) {
    const icons = {
        '.js': '📜',
        '.ts': '📘',
        '.tsx': '⚛️',
        '.jsx': '⚛️',
        '.py': '🐍',
        '.html': '📄',
        '.css': '🎨',
        '.json': '📦',
        '.md': '📝',
        '.yml': '📋',
        '.yaml': '📋',
        '.env': '⚙️',
        '.log': '📋',
        '.txt': '📄',
        '.tf': '🏗️'
    };
    
    for (const [ext, icon] of Object.entries(icons)) {
        if (filename.endsWith(ext)) return icon;
    }
    
    if (filename.includes('.')) return '📄';
    return '📁';
}

// DOM Elements
const fileTree = document.getElementById('file-tree');
const gitignoreContent = document.getElementById('gitignore-content');
const gitignoreInput = document.getElementById('gitignore-input');
const lineNumbers = document.getElementById('line-numbers');
const timerDisplay = document.getElementById('timer');
const scoreDisplay = document.getElementById('score');
const progressDisplay = document.getElementById('progress');
const levelIndicator = document.getElementById('level-indicator');
const modeIndicator = document.getElementById('mode-indicator');
const overlay = document.getElementById('overlay');
const overlayTitle = document.getElementById('overlay-title');
const overlayMessage = document.getElementById('overlay-message');
const overlayStats = document.getElementById('overlay-stats');
const startScreen = document.getElementById('start-screen');
const previewPanel = document.getElementById('preview-panel');
const previewContent = document.getElementById('preview-content');

// Initialize game
function init() {
    document.getElementById('btn-normal').addEventListener('click', () => startGame('normal'));
    document.getElementById('btn-pro').addEventListener('click', () => startGame('pro'));
    document.getElementById('btn-retry').addEventListener('click', retryLevel);
    document.getElementById('btn-next').addEventListener('click', nextLevel);
    document.getElementById('close-preview').addEventListener('click', closePreview);
    
    gitignoreInput.addEventListener('keydown', handleInput);
}

function startGame(mode) {
    gameState.mode = mode;
    gameState.currentLevel = 0;
    gameState.score = 0;
    startScreen.classList.add('hidden');
    
    if (mode === 'pro') {
        document.getElementById('game-container').classList.add('pro-mode');
        modeIndicator.textContent = '🔥 Pro Mode';
    } else {
        document.getElementById('game-container').classList.remove('pro-mode');
        modeIndicator.textContent = 'Normal Mode';
    }
    
    loadLevel(gameState.currentLevel);
}

function loadLevel(levelIndex) {
    const level = levels[levelIndex];
    if (!level) {
        showGameComplete();
        return;
    }
    
    // Reset state
    gameState.ignoredFiles = [];
    gameState.wrongAttempts = 0;
    gameState.startTime = Date.now();
    
    // Clear UI
    gitignoreContent.innerHTML = '';
    fileTree.innerHTML = '';
    closePreview();
    
    // Update indicators
    levelIndicator.textContent = `Level ${levelIndex + 1}: ${level.name}`;
    updateLineNumbers();
    updateProgress();
    
    // Render files
    level.files.forEach(file => {
        const fileEl = document.createElement('div');
        fileEl.className = 'file-item';
        fileEl.dataset.name = file.name;
        fileEl.dataset.shouldIgnore = file.shouldIgnore;
        
        fileEl.innerHTML = `
            <span class="icon">${file.icon || getFileIcon(file.name)}</span>
            <span class="name">${file.name}</span>
            ${file.shouldIgnore 
                ? '<span class="badge should-ignore">IGNORE</span>' 
                : '<span class="badge keep">KEEP</span>'}
        `;
        
        fileEl.addEventListener('click', () => showFilePreview(file));
        fileTree.appendChild(fileEl);
    });
    
    // Start timer
    if (gameState.timerInterval) clearInterval(gameState.timerInterval);
    gameState.timerInterval = setInterval(updateTimer, 100);
    
    // Focus input
    gitignoreInput.focus();
}

function handleInput(e) {
    if (e.key === 'Enter') {
        e.preventDefault();
        const filename = gitignoreInput.value.trim();
        if (!filename) return;
        
        addToGitignore(filename);
        gitignoreInput.value = '';
    }
}

function addToGitignore(filename) {
    const level = levels[gameState.currentLevel];
    const file = level.files.find(f => f.name === filename || f.name.toLowerCase() === filename.toLowerCase());
    
    // Check if already ignored
    if (gameState.ignoredFiles.includes(filename)) {
        showInputError('Already in .gitignore!');
        return;
    }
    
    // Check if file exists
    if (!file) {
        showInputError('File not found!');
        gameState.wrongAttempts++;
        return;
    }
    
    // Add entry to .gitignore display
    const entry = document.createElement('div');
    entry.className = 'gitignore-entry';
    entry.textContent = filename;
    
    if (!file.shouldIgnore) {
        // Wrong! This file shouldn't be ignored
        entry.classList.add('wrong');
        gameState.wrongAttempts++;
        gameState.score = Math.max(0, gameState.score - 50);
        
        // Mark file as wrong in tree
        const fileEl = document.querySelector(`.file-item[data-name="${file.name}"]`);
        if (fileEl) {
            fileEl.classList.add('wrong');
            setTimeout(() => fileEl.classList.remove('wrong'), 300);
        }
        
        // Remove wrong entry after animation
        gitignoreContent.appendChild(entry);
        setTimeout(() => entry.remove(), 500);
    } else {
        // Correct!
        gameState.ignoredFiles.push(filename);
        gameState.score += 100;
        gitignoreContent.appendChild(entry);
        
        // Mark file as ignored in tree
        const fileEl = document.querySelector(`.file-item[data-name="${file.name}"]`);
        if (fileEl) {
            fileEl.classList.add('ignored');
        }
        
        updateLineNumbers();
        updateProgress();
        
        // Check if level complete
        const filesToIgnore = level.files.filter(f => f.shouldIgnore).length;
        if (gameState.ignoredFiles.length >= filesToIgnore) {
            levelComplete();
        }
    }
    
    scoreDisplay.textContent = `Score: ${gameState.score}`;
}

function showInputError(message) {
    const originalPlaceholder = gitignoreInput.placeholder;
    gitignoreInput.placeholder = message;
    gitignoreInput.classList.add('error');
    
    setTimeout(() => {
        gitignoreInput.placeholder = originalPlaceholder;
        gitignoreInput.classList.remove('error');
    }, 1000);
}

function updateLineNumbers() {
    const count = gameState.ignoredFiles.length + 1;
    lineNumbers.innerHTML = Array.from({length: count}, (_, i) => i + 1).join('<br>');
}

function updateTimer() {
    const elapsed = (Date.now() - gameState.startTime) / 1000;
    timerDisplay.textContent = `Time: ${elapsed.toFixed(1)}s`;
}

function updateProgress() {
    const level = levels[gameState.currentLevel];
    const total = level.files.filter(f => f.shouldIgnore).length;
    progressDisplay.textContent = `${gameState.ignoredFiles.length} / ${total} files ignored`;
}

function showFilePreview(file) {
    previewPanel.classList.add('visible');
    
    let content = file.content;
    
    // In pro mode, highlight potential API keys / secrets
    if (gameState.mode === 'pro') {
        // Highlight things that look like API keys or secrets
        content = content.replace(
            /(sk_live_[a-zA-Z0-9]+|sk_test_[a-zA-Z0-9]+|sk-proj-[a-zA-Z0-9]+|AKIA[A-Z0-9]{16}|ghp_[a-zA-Z0-9]+|npm_[a-zA-Z0-9]+|-----BEGIN[^-]+PRIVATE KEY-----|whsec_[a-zA-Z0-9]+|SG\.[a-zA-Z0-9]+)/g,
            '<span class="api-key">$1</span>'
        );
    }
    
    previewContent.innerHTML = `<strong>${file.name}</strong>\n\n${content}`;
}

function closePreview() {
    previewPanel.classList.remove('visible');
}

function levelComplete() {
    clearInterval(gameState.timerInterval);
    const elapsed = (Date.now() - gameState.startTime) / 1000;
    
    // Bonus points for speed
    const timeBonus = Math.max(0, Math.floor((60 - elapsed) * 10));
    // Penalty for wrong attempts
    const penalty = gameState.wrongAttempts * 25;
    
    const levelScore = gameState.score + timeBonus - penalty;
    gameState.score = Math.max(0, levelScore);
    
    overlayTitle.textContent = '✅ Level Complete!';
    overlayTitle.style.color = '#4ec9b0';
    overlayMessage.textContent = `You completed "${levels[gameState.currentLevel].name}"`;
    overlayStats.innerHTML = `
        <div>⏱️ Time: ${elapsed.toFixed(1)}s</div>
        <div>🎯 Time Bonus: +${timeBonus}</div>
        <div>❌ Wrong Attempts: ${gameState.wrongAttempts} (-${penalty})</div>
        <div style="font-size: 24px; margin-top: 15px;">🏆 Score: ${gameState.score}</div>
    `;
    
    const btnNext = document.getElementById('btn-next');
    if (gameState.currentLevel >= levels.length - 1) {
        btnNext.textContent = 'Finish Game';
    } else {
        btnNext.textContent = 'Next Level';
    }
    
    overlay.classList.remove('hidden');
}

function showGameComplete() {
    overlayTitle.textContent = '🎉 Congratulations!';
    overlayTitle.style.color = '#cca700';
    overlayMessage.textContent = 'You completed all levels!';
    overlayStats.innerHTML = `
        <div style="font-size: 28px;">🏆 Final Score: ${gameState.score}</div>
        <div style="margin-top: 20px; color: #858585;">
            ${gameState.mode === 'pro' ? '🔥 Pro Mode Completed!' : 'Try Pro Mode for an extra challenge!'}
        </div>
    `;
    
    document.getElementById('btn-next').style.display = 'none';
    document.getElementById('btn-retry').textContent = 'Play Again';
    
    overlay.classList.remove('hidden');
}

function retryLevel() {
    overlay.classList.add('hidden');
    document.getElementById('btn-next').style.display = '';
    document.getElementById('btn-retry').textContent = 'Retry';
    
    if (gameState.currentLevel >= levels.length) {
        // Restart game
        gameState.currentLevel = 0;
        gameState.score = 0;
    }
    
    loadLevel(gameState.currentLevel);
}

function nextLevel() {
    overlay.classList.add('hidden');
    gameState.currentLevel++;
    loadLevel(gameState.currentLevel);
}

// Initialize on load
init();
